language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test_xunit
  - make lint
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app: ancient-savannah-34573
